#!/bin/sh

REPO_PATH=$(/usr/bin/git rev-parse --show-toplevel)
/usr/bin/python3 -m black $REPO_PATH --line-length 120 --target-version py310
/usr/bin/python3 -m isort $REPO_PATH
/usr/bin/git update-index --again :/: