services:

  sned-db:
    image: postgres:${POSTGRES_VERSION:-14}
    restart: always
    expose:
      - ${POSTGRES_PORT:-5432}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-sned}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private

  sned:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        postgres_version: ${POSTGRES_VERSION:-14}
    environment:
      TOKEN: ${TOKEN:?err}
      DEV_MODE: ${DEV_MODE:-false}
      ERROR_LOGGING_CHANNEL: ${ERROR_LOGGING_CHANNEL:-}
      DB_BACKUP_CHANNEL: ${DB_BACKUP_CHANNEL:-}
      DEBUG_GUILDS: ${DEBUG_GUILDS:-}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_HOST: sned-db
      POSTGRES_DB: ${POSTGRES_DB:-sned}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      PERSPECTIVE_API_KEY: ${PERSPECTIVE_API_KEY:?err}
      DICTIONARYAPI_API_KEY: ${DICTIONARYAPI_API_KEY:?err}
    depends_on:
      - sned-db
    restart: always
    networks:
      - private

networks:
  private:
    external: false

volumes:
  postgres_data:
